catalogs:
  dep:
    next: ^15.5.5
    react: ^19.2.0
    react-dom: ^19.2.0
  dev:
    "@types/node": ^24.7.2
    "@types/react": ^19.2.2
    "@types/react-dom": ^19.2.2
    sass: ^1.93.2
    typescript: ^5.9.3

onlyBuiltDependencies:
  - "@parcel/watcher"
  - sharp
