catalogs:
  dev:
    "@types/node": ^24.7.2
    chalk: ^5.6.2
    consola: ^3.4.2
    glob: ^11.0.3
    tsx: ^4.20.6
    typescript: ^5.9.3

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
