catalogs:
  dev:
    "@types/node": ^24.8.0
    chalk: ^5.6.2
    consola: ^3.4.2
    dotenv: ^17.2.3
    glob: ^11.0.3
    tsx: ^4.20.6
    typescript: ^5.9.3

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
