name: review

on:
  pull_request: { branches: ["main"] }

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        with: { version: 10 }
      - run: pnpm install
      - run: pnpm review
      - run: pnpm test
      - run: pnpm build
